-- 첨부 게시판

-- 1. 단일 첨부
/*
    게시글1 - 첨부1
    
    게시판 : 제목, 내용, 작성자, 첨부파일명, 경로 등
*/

-- 2. 다중 첨부
/*
    
    게시글1 - 첨부1
            - 첨부2
    
    게시판 : 번호(PK), 제목, 내용, 작성자
             
    첨부   : 첨부번호, 게시글 번호(FK), 첨부 파일명, 경로

*/
DROP TABLE FILE_ATTACH;
CREATE TABLE FILE_ATTACH
(
    FILE_ATTACH_NO NUMBER NOT NULL,
    PATH VARCHAR2(300 BYTE),
    ORIGIN VARCHAR2(300 BYTE),
    SAVED VARCHAR2(40 BYTE),
    DOWNLOAD_CNT NUMBER,
    GALLERY_NO NUMBER
);
DROP TABLE GALLERY;
CREATE TABLE GALLERY
(
    GALLERY_NO NUMBER NOT NULL,
    WRITER VARCHAR2(50 BYTE),
    TITLE VARCHAR2(100 BYTE),
    CONTENT VARCHAR2(100 BYTE),
    IP VARCHAR2(30 BYTE),
    HIT NUMBER,
    CREATED DATE,
    MODIFIED DATE
);

ALTER TABLE GALLERY 
    ADD CONSTRAINT GALLERY_PK PRIMARY KEY(GALLERY_NO);
        
ALTER TABLE FILE_ATTACH 
    ADD CONSTRAINT FILE_ATTACH_PK PRIMARY KEY(FILE_ATTACH_NO);
        
ALTER TABLE FILE_ATTACH
    ADD CONSTRAINT FILE_ATTACH_FK 
        FOREIGN KEY(GALLERY_NO) REFERENCES GALLERY(GALLERY_NO)
            ON DELETE CASCADE;  --게시글 삭제하면 첨부 내역이 삭제

DROP SEQUENCE GALLERY_SEQ;
CREATE SEQUENCE GALLERY_SEQ NOCACHE;

DROP SEQUENCE FILE_ATTACH_SEQ;
CREATE SEQUENCE FILE_ATTACH_SEQ NOCACHE;